backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Home Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Titel, name: titel, widget: string }
          - { label: Image, name: image, widget: image }
          - {
              label: 'Over ons',
              name: overOns,
              widget: object,
              fields:
                [
                  { label: Titel, name: titel, widget: string },
                  { label: Text, name: text, widget: markdown },
                ],
            }

          - {
              label: Activiteiten,
              name: activiteiten,
              widget: object,
              fields:
                [
                  { label: Titel, name: titel, widget: string },
                  { label: Text, name: text, widget: markdown },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Titel, name: titel, widget: string },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }

          - {
              label: Banner,
              name: banner,
              widget: object,
              fields: [{ label: Text, name: text, widget: string }],
            }

          - {
              label: Tinnewerck,
              name: tinnewerck,
              widget: object,
              fields:
                [
                  { label: Titel, name: titel, widget: string },
                  { label: Text, name: text, widget: text },
                  {
                    label: edities,
                    name: edities,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Contact,
              name: contact,
              widget: object,
              fields:
                [
                  { label: Tel, name: tel, widget: string },
                  { label: Email, name: email, widget: string },
                  {
                    label: Links,
                    name: links,
                    widget: list,
                    fields:
                      [
                        { label: Url, name: url, widget: string },
                        { label: Text, name: text, widget: string },
                      ],
                  },
                ],
            }
      - file: 'src/pages/vragen.md'
        label: 'Vragen'
        name: 'vragen'
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Beschrijving, name: description, widget: 'text' }
      - file: 'src/pages/archief.md'
        label: 'Archief'
        name: 'archief'
        fields:
          - { label: Titel, name: titel, widget: string }
          - {
              label: Edities,
              name: edities,
              widget: list,
              fields:
                [
                  { label: Nummer, name: nummer, widget: number },
                  { label: Titel, name: titel, widget: string },
                  { label: Text, name: text, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
